#!/bin/bash

POOL=/home/mic/.pool
LLVM_OMP_BUILD_DIR=$POOL/.build/.llvm-openmp_nightly_`date "+%Y%m%d"`
LLVM_OMP_SRC_DIR=$POOL/.src/llvm-openmp
LLVM_OMP_PREFIX_BASE=$POOL/llvm-openmp
LLVM_OMP_NIGHTLY_DIR=$POOL/llvm-openmp/nightly
LLVM_OMP_OLD_NIGHTLY_DIRS=$HOME/scratch/.old_nightly/llvm-openmp
KEEP_OLD_NIGHTLY=10

# Execute command with parameters and quit if it failed
exec_or_die() {
  eval $*
  if [ $? -ne 0 ]; then
    echo "error in file $0, line ${BASH_LINENO[0]}: failed to execute '$@'" >&2
    exit 1
  fi
}

# Mark beginning
date

echo "################################################################################"
echo "Updating svn sources..."
echo "################################################################################"
exec_or_die svn update $LLVM_OMP_SRC_DIR

echo
echo "################################################################################"
echo "Determining revision..."
echo "################################################################################"
rev=`svn info $LLVM_OMP_SRC_DIR | awk '/^Revision/ {print $2}'`
if echo $rev | grep -vq '^[0-9][0-9]*$'; then
  echo "error: bad revision number: $rev" >&2
  exit 1
fi
echo "Revision: $rev"
llvm_omp_install_dir=$LLVM_OMP_PREFIX_BASE/`date "+%Y%m%d"`-r$rev
echo "Install dir: $llvm_omp_install_dir"
if [ -d "$llvm_omp_install_dir" ]; then
  echo "LLVM OpenMP is up to date, nothing to do."
  exit 0
fi

echo
echo "################################################################################"
echo "Recreating build dir..."
echo "################################################################################"
echo "Build dir: $LLVM_OMP_BUILD_DIR"
exec_or_die rm -rf "$LLVM_OMP_BUILD_DIR"
exec_or_die mkdir -p "$LLVM_OMP_BUILD_DIR"

echo
echo "################################################################################"
echo "Running configure..."
echo "################################################################################"
cmd="cmake -G \"Unix Makefiles\" \
    -DCMAKE_C_COMPILER=gcc \
    -DCMAKE_CXX_COMPILER=g++ \
    $LLVM_OMP_SRC_DIR"
echo "Configure command: $cmd"
exec_or_die pushd $LLVM_OMP_BUILD_DIR
exec_or_die $cmd
exec_or_die popd

echo
echo "################################################################################"
echo "Building and installing..."
echo "################################################################################"
exec_or_die pushd $LLVM_OMP_BUILD_DIR
exec_or_die make all common -j 10
exec_or_die make install
exec_or_die popd
exec_or_die rm -rf "$LLVM_OMP_BUILD_DIR"

echo
echo "################################################################################"
echo "Resetting nightly version..."
echo "################################################################################"
old_nightly_dir=$([ -d $LLVM_OMP_NIGHTLY_DIR ] && cd $LLVM_OMP_NIGHTLY_DIR \
    && pwd -P)
echo "Old nightly install: $old_nightly_dir"
exec_or_die rm -f $LLVM_OMP_NIGHTLY_DIR
exec_or_die ln -s $llvm_omp_install_dir $LLVM_OMP_NIGHTLY_DIR

echo
echo "################################################################################"
echo "Cleaning up old nightly installs..."
echo "################################################################################"
exec_or_die [ -d "$old_nightly_dir" ] \
    && mv $old_nightly_dir $LLVM_OMP_OLD_NIGHTLY_DIRS
exec_or_die find $LLVM_OMP_OLD_NIGHTLY_DIRS -mindepth 1 -maxdepth 1 | sort \
    | head -n -$KEEP_OLD_NIGHTLY | xargs rm -rf

# Mark end
date
